package com.everydaypratic;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT.
 */
public class Student {

    private double LearnNumber;
    private Short Name;
    private String Sex;
    private Double Age;
    private Double Number;

    public Student() {
    }

    public Student(double LearnNumber) {
        this.LearnNumber = LearnNumber;
    }

    public Student(double LearnNumber, Short Name, String Sex, Double Age, Double Number) {
        this.LearnNumber = LearnNumber;
        this.Name = Name;
        this.Sex = Sex;
        this.Age = Age;
        this.Number = Number;
    }

    public double getLearnNumber() {
        return LearnNumber;
    }

    public void setLearnNumber(double LearnNumber) {
        this.LearnNumber = LearnNumber;
    }

    public Short getName() {
        return Name;
    }

    public void setName(Short Name) {
        this.Name = Name;
    }

    public String getSex() {
        return Sex;
    }

    public void setSex(String Sex) {
        this.Sex = Sex;
    }

    public Double getAge() {
        return Age;
    }

    public void setAge(Double Age) {
        this.Age = Age;
    }

    public Double getNumber() {
        return Number;
    }

    public void setNumber(Double Number) {
        this.Number = Number;
    }

}
